# Generated by Django 5.2.13 on 2026-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='country',
            field=models.CharField(default='Algérie', max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_projet',
            field=models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('LOGEMENT', 'Logement'), ('COMMERCE', 'Commerce'), ('INDUSTRIEL', 'Industriel'), ('EQUIPEMENT', 'Équipement public'), ('PAYSAGISME', 'Paysagisme'), ('RENOVATION', 'Rénovation'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
