# Generated by Django 5.2.13 on 2026-05-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
        ('projets', '0004_feuilledetemps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_prestation', models.CharField(choices=[('BET_STRUCTURE', 'BET Structure'), ('BET_FLUIDES', 'BET Fluides'), ('ECONOMISTE', 'Économiste'), ('GEOMETRE', 'Géomètre'), ('GEOTECHNIQUE', 'Géotechnique'), ('ELECTRICIEN', 'Électricien'), ('PLOMBIER', 'Plombier'), ('MENUISIER', 'Menuisier'), ('PEINTRE', 'Peintre'), ('AUTRE', 'Autre')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('montant_contrat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_traitants', to='cabinets.cabinet')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_traitants', to='projets.projet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
