# Generated by Django 6.0.4 on 2026-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_soustraitant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='client',
            name='rc',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='country',
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='adresse_chantier',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_projet',
            field=models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('LOGEMENT', 'Logement'), ('COMMERCE', 'Commerce'), ('INDUSTRIEL', 'Industriel'), ('EQUIPEMENT', 'Équipement public'), ('PAYSAGISME', 'Paysagisme'), ('RENOVATION', 'Rénovation'), ('AUTRE', 'Autre')], default='RESIDENTIEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='wilaya',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
