# Generated by Django 6.0.4 on 2026-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_remove_client_nif_remove_client_rc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_nom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='nis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_rc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
