# Generated by Django 6.0.4 on 2026-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_client_ai_client_contact_nom_client_nif_client_nis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('SUSPENDU', 'Suspendu')], default='A_FAIRE', max_length=10),
        ),
    ]
