# Generated by Django 6.0.4 on 2026-05-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_alter_phase_nom_execution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soustraitant',
            old_name='montant_contrat',
            new_name='montant_devis',
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='montant_facture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20),
        ),
    ]
