# Generated by Django 6.0.4 on 2026-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0013_simplify_soustraitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuilledetemps',
            name='taches',
            field=models.ManyToManyField(blank=True, related_name='feuilles', to='projets.tache'),
        ),
    ]
