# Generated by Django 6.0.4 on 2026-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0014_feuille_taches_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feuilledetemps',
            name='taches',
        ),
        migrations.DeleteModel(
            name='Tache',
        ),
    ]
