# Generated by Django 5.2.13 on 2026-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meteo', models.CharField(choices=[('SOLEIL', 'Ensoleillé'), ('NUAGEUX', 'Nuageux'), ('PLUIE', 'Pluie'), ('VENT', 'Vent')], max_length=20)),
                ('effectif', models.IntegerField(default=0)),
                ('avancement', models.IntegerField(default=0)),
                ('travaux_realises', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chantier/photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('responsable', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours de levée'), ('LEVEE', 'Levée')], default='OUVERTE', max_length=10)),
                ('date_constat', models.DateField(auto_now_add=True)),
                ('date_levee', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reserves/')),
            ],
        ),
    ]
