# Generated by Django 5.2.13 on 2026-04-22 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0003_initial'),
        ('projets', '0003_projet_country_alter_projet_type_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ordre', models.CharField(choices=[('DEMARRAGE', 'Ordre de démarrage'), ('ARRET', 'Ordre d arrêt'), ('REPRISE', 'Ordre de reprise'), ('MODIFICATION', 'Ordre de modification')], max_length=20)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_service', to='projets.projet')),
            ],
        ),
    ]
