# Generated by Django 5.2.13 on 2026-05-01 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0004_ordreservice'),
        ('projets', '0004_feuilledetemps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('meteo', models.CharField(default='SOLEIL', max_length=20)),
                ('etat_general', models.CharField(choices=[('BON', 'Bon'), ('ACCEPTABLE', 'Acceptable'), ('MAUVAIS', 'Mauvais'), ('CRITIQUE', 'Critique')], default='BON', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('securite_ok', models.BooleanField(default=True)),
                ('structure_ok', models.BooleanField(default=True)),
                ('electricite_ok', models.BooleanField(default=True)),
                ('plomberie_ok', models.BooleanField(default=True)),
                ('etancheite_ok', models.BooleanField(default=True)),
                ('finitions_ok', models.BooleanField(default=True)),
                ('actions_requises', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_terrain', to='projets.projet')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
