# Generated by Django 5.2.13 on 2026-04-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('numero_oaa', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Basique', 'Basique-2900'), ('Pro', 'Pro-5900'), ('Premium', 'Premium-10900')], default='Basique', max_length=20)),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='cabinets.cabinet')),
            ],
        ),
    ]
