# Generated by Django 6.0.4 on 2026-05-06 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='date_debut',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='plan',
            field=models.CharField(choices=[('SOLO', 'Solo - 2 900 DA/mois'), ('CABINET', 'Cabinet - 5 900 DA/mois'), ('PREMIUM', 'Premium - 9 900 DA/mois')], default='SOLO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
