# Generated by Django 6.0.4 on 2026-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0002_abonnement_actif_abonnement_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='activite',
            field=models.CharField(blank=True, default="Cabinet d'Architecture", max_length=200),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='ai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='nif',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='nis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='numero_rc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='numero_oaa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
