# Generated by Django 6.0.4 on 2026-05-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_cabinet_activite_cabinet_ai_cabinet_nif_cabinet_nis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='numero_oaa',
        ),
    ]
