# Generated by Django 6.0.4 on 2026-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_remove_cabinet_numero_oaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
