# Generated by Django 6.0.4 on 2026-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0005_abonnement_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='plan',
            field=models.CharField(choices=[('SOLO', 'Solo - 2 900 DA/mois'), ('CABINET', 'Cabinet - 6 900 DA/mois'), ('AGENCE', 'Agence - 13 900 DA/mois')], default='SOLO', max_length=20),
        ),
    ]
