# Generated by Django 6.0.4 on 2026-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0006_rename_premium_to_agence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='plan',
            field=models.CharField(choices=[('SOLO', 'Solo - 3 900 DA/mois'), ('CABINET', 'Cabinet - 7 900 DA/mois'), ('AGENCE', 'Agence - 14 900 DA/mois')], default='SOLO', max_length=20),
        ),
    ]
