# Generated by Django 6.0.4 on 2026-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0007_alter_abonnement_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='wilaya',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
