# Generated by Django 6.0.4 on 2026-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0008_add_wilaya_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='assujetti_tva',
            field=models.BooleanField(default=True),
        ),
    ]
