# Generated by Django 6.0.4 on 2026-05-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_cabinet_assujetti_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('cabinet', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('sujet', models.CharField(choices=[('DEMO', 'Demande de démo'), ('TARIF', 'Question tarifaire'), ('SUPPORT', 'Support technique'), ('PARTENARIAT', 'Partenariat'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
