# Generated by Django 6.0.6 on 2026-06-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0010_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('HEBERGEMENT', 'Hébergement'), ('EMAIL', 'Email/Resend'), ('STOCKAGE', 'Cloudflare R2'), ('DOMAINE', 'Domaine'), ('SALAIRES', 'Salaires'), ('MARKETING', 'Marketing'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField()),
                ('recurrent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
