# Generated by Django 6.0.6 on 2026-06-21 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0011_platformcharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('canal', models.CharField(choices=[('INAPP', 'In-app'), ('EMAIL', 'Email'), ('LES_DEUX', 'Les deux')], default='LES_DEUX', max_length=10)),
                ('cible', models.CharField(choices=[('TOUS', 'Tous'), ('SOLO', 'SOLO'), ('CABINET', 'CABINET'), ('AGENCE', 'AGENCE')], default='TOUS', max_length=10)),
                ('destinataires', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
