# Generated by Django 6.0.6 on 2026-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0012_annonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(max_length=200)),
                ('cible', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('Error', 'Error'), ('Warning', 'Warning'), ('Info', 'Info')], default='Error', max_length=10)),
                ('message', models.CharField(max_length=300)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('contexte', models.TextField(blank=True, default='')),
                ('occurrences', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
