# Generated by Django 6.0.6 on 2026-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0013_activitylog_systemerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('populaire', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list)),
                ('max_users', models.IntegerField(default=1)),
                ('max_projets', models.IntegerField(default=30)),
                ('stockage_gb', models.IntegerField(default=5)),
                ('f_planning', models.BooleanField(default=False)),
                ('f_soustraitants', models.BooleanField(default=False)),
                ('f_export_compta', models.BooleanField(default=False)),
                ('f_ia', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Planner', max_length=100)),
                ('email_contact', models.EmailField(default='contact@planner.dz', max_length=254)),
                ('devise', models.CharField(default='DA', max_length=10)),
                ('tva_defaut', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('maintenance', models.BooleanField(default=False)),
                ('inscriptions_ouvertes', models.BooleanField(default=True)),
            ],
        ),
    ]
