# Generated by Django 6.0.6 on 2026-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0015_seed_plan_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='plan',
            field=models.CharField(choices=[('SOLO', 'Solo - 4 900 DA/mois'), ('CABINET', 'Cabinet - 8 900 DA/mois'), ('AGENCE', 'Agence - 14 900 DA/mois')], default='SOLO', max_length=20),
        ),
    ]
