# Generated by Django 6.0.6 on 2026-06-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0016_alter_abonnement_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='repondu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='repondu_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reponse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
