# Generated by Django 5.2.13 on 2026-04-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('ENVOYEE', 'Envoyée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('SOLDEE', 'Soldée'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=25)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('CCP', 'CCP')], max_length=20)),
                ('date_paiement', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_validite', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinet')),
            ],
        ),
    ]
