# Generated by Django 5.2.13 on 2026-04-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0001_initial'),
        ('finances', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.client'),
        ),
        migrations.AddField(
            model_name='devis',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
        ),
        migrations.AddField(
            model_name='facture',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinet'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projets.phase'),
        ),
        migrations.AddField(
            model_name='facture',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.facture'),
        ),
    ]
