# Generated by Django 5.2.13 on 2026-04-22 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
        ('finances', '0002_initial'),
        ('projets', '0003_projet_country_alter_projet_type_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('DEPLACEMENT', 'Déplacement'), ('CARBURANT', 'Carburant / Essence'), ('ACCIDENT', 'Accident / Assurance'), ('LOYER', 'Loyer local'), ('MOBILIER', 'Mobilier / Équipement'), ('LOGICIEL', 'Logiciels / Abonnements'), ('SALAIRE', 'Salaires'), ('IMPOTS', 'Impôts / Taxes'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='charges/')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cabinets.cabinet')),
                ('paye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='projets.projet')),
            ],
        ),
    ]
