# Generated by Django 6.0.4 on 2026-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
