# Generated by Django 6.0.4 on 2026-05-18 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0007_alter_abonnement_plan'),
        ('finances', '0004_auto_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paie', models.CharField(choices=[('MENSUEL', 'Mensuel fixe'), ('JOURNALIER', 'Journalier'), ('FORFAIT', 'Forfait libre')], default='MENSUEL', max_length=20)),
                ('taux', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_paie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mois', models.IntegerField()),
                ('periode_annee', models.IntegerField()),
                ('type_paie', models.CharField(max_length=20)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nb_jours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='cabinets.cabinet')),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_paie', to='finances.charge')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periode_annee', '-periode_mois'],
                'unique_together': {('cabinet', 'membre', 'periode_mois', 'periode_annee')},
            },
        ),
    ]
