# Generated by Django 6.0.4 on 2026-05-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_configpaie_fichepaie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='tva',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='tva',
        ),
        migrations.AddField(
            model_name='devis',
            name='conditions_paiement',
            field=models.CharField(choices=[('RECEPTION', 'À réception'), ('30J', '30 jours'), ('45J', '45 jours'), ('60J', '60 jours'), ('PERSONNALISE', 'Personnalisé')], default='30J', max_length=20),
        ),
        migrations.AddField(
            model_name='devis',
            name='mentions_legales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devis',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='devis',
            name='rib',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='facture',
            name='conditions_paiement',
            field=models.CharField(choices=[('RECEPTION', 'À réception'), ('30J', '30 jours'), ('45J', '45 jours'), ('60J', '60 jours'), ('PERSONNALISE', 'Personnalisé')], default='30J', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='mentions_legales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='rib',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('ENVOYEE', 'Envoyée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('SOLDEE', 'Soldée'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=25),
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=500)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.devis')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=500)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.facture')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
