# Generated by Django 6.0.4 on 2026-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_migrate_lignes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='phase',
        ),
        migrations.AlterField(
            model_name='configpaie',
            name='type_paie',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel fixe'), ('JOURNALIER', 'Journalier')], default='MENSUEL', max_length=20),
        ),
    ]
