# Generated by Django 6.0.4 on 2026-05-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_remove_facture_phase_alter_configpaie_type_paie'),
        ('projets', '0015_remove_feuilledetemps_taches_delete_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projets.phase'),
        ),
    ]
