# Generated by Django 5.2.13 on 2026-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propriétaire'), ('ARCHITECTE', 'Architecte'), ('DESSINATEUR', 'Dessinateur'), ('COMPTABLE', 'Comptable')], default='ARCHITECTE', max_length=20),
        ),
    ]
