# Generated by Django 5.2.13 on 2026-04-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propriétaire'), ('ARCHITECTE', 'Architecte'), ('DESSINATEUR', 'Dessinateur'), ('COMPTABLE', 'Comptable')], default='OWNER', max_length=20),
        ),
    ]
