# Generated by Django 6.0.4 on 2026-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propriétaire'), ('ARCHITECTE', 'Architecte'), ('DESSINATEUR', 'Dessinateur'), ('COMPTABLE', 'Comptable')], default='ARCHITECTE', max_length=20),
        ),
    ]
