# Generated by Django 6.0.4 on 2026-05-15 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0007_alter_abonnement_plan'),
        ('projets', '0008_tache_add_statuts_annule_suspendu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('CONTRAT', "Contrat de maîtrise d'œuvre"), ('AVENANT', 'Avenant')], default='CONTRAT', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('SIGNE', 'Signé'), ('RESILIE', 'Résilié')], default='BROUILLON', max_length=20)),
                ('objet', models.TextField()),
                ('missions', models.JSONField(default=list)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='cabinets.cabinet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='projets.client')),
                ('contrat_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avenants', to='contrats.contrat')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='projets.projet')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
