# Generated by Django 6.0.4 on 2026-05-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='contrats.contrat')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
