# Generated by Django 6.0.4 on 2026-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_cabinet_assujetti_tva'),
        ('contrats', '0003_migrate_articles_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='contrat',
            unique_together={('cabinet', 'numero')},
        ),
    ]
