# Generated by Django 5.2.13 on 2026-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('PLAN', 'Plan'), ('PERMIS', 'Permis de construire'), ('DCE', 'DCE'), ('CCTP', 'CCTP'), ('RAPPORT', 'Rapport'), ('CONTRAT', 'Contrat'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.IntegerField()),
                ('fichier', models.FileField(upload_to='documents/')),
                ('taille', models.IntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-numero_version'],
            },
        ),
    ]
