# Generated by Django 5.2.13 on 2026-04-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projets.projet'),
        ),
    ]
