# Generated by Django 5.2.13 on 2026-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('PLAN', 'Plan'), ('PERMIS', 'Permis de construire'), ('DCE', 'DCE'), ('CCTP', 'CCTP'), ('RAPPORT', 'Rapport'), ('CONTRAT', 'Contrat'), ('AVENANT', 'Avenant'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
